default:
	@echo 'default'
	gcc -Wall -std=c99 pipe.c -o pipe.o

pread:
	@echo "pread"
	gcc -Wall -std=c99 pread.c -o pread.o

who:
	@echo "Who Count"
	gcc -Wall -std=c99 who_count.c -o w.o

sh:
	@echo "Shell"
	gcc -Wall -std=c99 -D_POSIX_C_SOURCE=200809L shell.c display.c -o sh.o
